name: Publish
on:
  release:
    types: [published]
jobs:
  psgallery_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Publishing
        run: |
                    Publish-Module -Path 'CitrixOptimizerAutomation' -NuGetApiKey ${{ secrets.PSGALLERY }}
        shell: pwsh
